### ISSUE TITLE
Add releases

### ISSUE THREAD

**Issue by lukasoppermann** [mitchas/ffftp#17]
Hey, it would be great if you could always release the current version via a tag on github including a downloadble version of the app.

**Comment by claudemuller** [comment]
Agreed! Added to the list thanks :)

**Comment by lukasoppermann** [comment]
Hey @claudemuller I know adding a downloadable app version is quite a bit of work, but could you maybe just start with tagging releases? This way one knows at least that one has the latest version that is deemed usable. 👍 

Thanks for working in this project.
