### ISSUE TITLE
How to upload?

### ISSUE THREAD

**Issue by skybldev** [mitchas/ffftp#23]
I can't find any button to upload any files to my server. Dragging and dropping only makes it say "Getting file tree..." on the bottom, but no new files are shown. How do I upload?

**Comment by v0112358** [comment]
I think this feature is not available at the moment.

**Comment by jonasgeiler** [comment]
Normally, drag and drop should work. Not sure what the issue is here...

**Comment by v0112358** [comment]
Drag and drop is not work on MacOS, it hangs at "getting file tree..". I will test upload on Windows.

**Comment by skybldev** [comment]
It tries to upload in Windows, but it just hangs.

**Comment by v0112358** [comment]
It also failed on Linux (Ubuntu).

The error message from Dev tool is:
"Uncaught ReferenceError: dirTree is not defined
    at HTMLBodyElement.document.body.ondrop (base.js:433)"
