### ISSUE TITLE
Allow for sftp.

### ISSUE THREAD

**Issue by lukasoppermann** [mitchas/ffftp#7]
Hey, I think an option to allow sftp would be very good. 

Maybe you could just add a toggle to turn it on or off?

**Comment by jslatt** [comment]
FTP function is built off of `jsftp-rmr` so I am not sure if it would be possible without rewriting the entire app.

**Comment by lukasoppermann** [comment]
Hmm, but an ftp app without sftp? This seems a pretty vital feature.

**Comment by claudemuller** [comment]
Hey guys

Agreed! I'll be looking into that this week :)

**Comment by ghost** [comment]
@mitchas would be amazing if this supported `sftp` 👍
