### ISSUE TITLE
UI/UX improvements.

### ISSUE THREAD

**Issue by lukasoppermann** [mitchas/ffftp#8]
Hey, I really like the idea of a very simple ftp client. And the very reduced look is awesome.

However I do have some suggestions to improve the UX. If you are interested I could upload a design to show the points mentioned.

1. Adding a feedback when dropping files onto the app (maybe a semi-transparent overlay saying "dropping X files")

2. Highlighting newly added files (at least for 30 secs or maybe until the next file is uploaded or the the user navigates) maybe in green.

3. Highlighting updated files (see above)

4. The favouriting features is a bit confusing. It is not really clear why the buttons shows an X and when a √. Also It is not clear how to edit favourites. I think this screen could be improved a bit.

**Comment by j-f1** [comment]
How about inlining the title bar on macOS so there isn’t a gray strip at the top?
